// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrIB80kVJwNojDRU9rq4zP_GOFFXV6M_w',
    appId: '1:68614719530:android:4f369af6bde6e5b7781b53',
    messagingSenderId: '68614719530',
    projectId: 'arduinoproject1-10e0b',
    databaseURL: 'https://arduinoproject1-10e0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arduinoproject1-10e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNcgPhjZTaye0NX0gfR9phfAJyacW2z4',
    appId: '1:68614719530:ios:1cff4903f4d11656781b53',
    messagingSenderId: '68614719530',
    projectId: 'arduinoproject1-10e0b',
    databaseURL: 'https://arduinoproject1-10e0b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arduinoproject1-10e0b.appspot.com',
    iosClientId: '68614719530-1va4i9dcek7iq31ebqft36hjfmgssf7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessmatesAdmin',
  );
}
